version: '3'
services:
  node:
    image: node:16
    container_name: react_18_rc
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:./node_modules/.bin
    ports:
      - 1818:3000
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: >
      sh -c '
        npm start
      '
