name: jest-run-pull-request

on:
  pull_request:

jobs:
  jest:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install npm
        run: npm install
      - name: Run jest
        run: npm run test
